"""MCP stdio server using newline-delimited JSON-RPC 2.0 (no runtime deps)."""
import json
import os
import sys

from . import __version__
from .index import Database
from .validate import Validator
from .projection import project

VERSIONS = ('2024-11-05', '2025-03-26', '2025-06-18', '2025-11-25')

# Injected into the client's system prompt on ``initialize``. The first paragraph is
# load-bearing: an agent that shells out to this server's own CLI, or that reads the
# bundled corpus itself, answers worse than one that calls these tools, so the
# directive comes before the semantics rather than after them.
INSTRUCTIONS = (
    'Answer Stellaris scripting questions with these tools -- stellaris_search, '
    'stellaris_list, stellaris_validate, stellaris_doctor -- not by running commands or '
    'reading files. Do not invoke this server\'s own CLI (stellaris_modder_tool.py, start.py, '
    'scripts/*), and do not open, grep or read the .cwt files under stellaris_modder_agent/data '
    'or the server source: the tools already hold the parsed corpus index, the call '
    'sites, the loaded game/mod data and the evidence rules, while the raw corpus is text '
    'with no status attached, so reading it spends more context for less certainty. Use '
    'the shell only for the user\'s own mod files, which these tools never edit. '
    'Evidence comes from two sources: the bundled CWT corpus (rules) and, when available, '
    'the installed game plus the script files of the manually configured mod '
    '(objects). Names: stellaris_search returns up to five {name,type,definitions} rows '
    'by default, split into results (evidence), templates (documented shapes) and '
    'suggestions (candidates); a suggestion definition proves only how the suggested '
    'spelling is declared, not that the misspelled query exists. Text: mode="text" '
    'searches literal game/mod script lines with cross-directory sampling; the returned '
    'value is the row count, has_more signals omitted confirmed hits, and total is '
    'present only when scan_complete is true. Files: stellaris_list() -> pick a real .cwt '
    'path -> stellaris_search(query=path); files up to 800 lines come back whole, while '
    'larger ones answer USE_SEARCH and require stellaris_search(query=identifier, '
    'type=path). Never guess paths. Statuses: CONFIRMED_CWT (declared by the rules), '
    'CONFIRMED_GAME_DATA (declared by the loaded game/mod data, or generated by the '
    'game), TEMPLATE_MATCH (only the documented shape matched), SUGGESTION (candidate '
    'only), UNKNOWN (no matching declaration in loaded sources). Treat UNKNOWN as the '
    'lookup result; retry only when you have a new name, source, or context. Game-generated '
    'modifiers and names declared by the mod resolve only while that data is loaded; '
    'stellaris_doctor reports configured sources. Typos are matched fuzzily against both '
    'sources, and '
    'newly written entries are picked up without restarting the server. After writing '
    'code, call stellaris_validate with an explicit context; a bare known schema name is '
    'accepted as schema context, and findings carry a one-line legend.'
)

TOOLS = [
    {'name': 'stellaris_search',
     'description': 'Find declarations and call sites in one call. Identifiers: name mode (default), type= filters by type, returns declaration plus call sites. Values, literals, event ids, localisation text: mode="text", which name mode cannot find; returns path:line rows, type= filters by directory. Only `results` are evidenced.',
     'inputSchema': {'type': 'object', 'properties': {'query': {'type': 'string'}, 'type': {'type': 'string'},
                     'limit': {'type': 'integer', 'minimum': 1, 'maximum': 500, 'default': 5,
                               'description': 'Defaults to 5. Name mode accepts at most 10 because every row includes its declaration; text mode accepts up to 500.'},
                     'mode': {'type': 'string', 'enum': ['name', 'text'],
                              'description': 'name (default) ranks matching identifiers; text searches the raw game/mod script text and returns file:line with the matching line, with an optional type= directory filter.'},
                     'detail': {'type': 'boolean',
                                'description': 'Deprecated: accepted and ignored. Every call returns the one compact shape.'}},
                     'required': ['query'], 'additionalProperties': False}},
    {'name': 'stellaris_list',
     'description': 'List all bundled relative CWT paths, with no per-file metadata. Select a real path, then pass it as stellaris_search(query="common/buildings.cwt"). Do not guess paths. Root and subdirectory files share an 800-line whole-file limit; oversized files require a name search with type set to that path.',
     'inputSchema': {'type': 'object', 'properties': {}, 'required': [], 'additionalProperties': False}},
    {'name': 'stellaris_validate',
     'description': 'Check script against the loaded rules: identifiers, nested fields/aliases, values, templates, explicit cardinality and static scopes; with game/mod data loaded, game-generated and mod-declared names resolve as CONFIRMED_GAME_DATA. context can be a type string, or {type,schema,scope,mode}; mode defaults to body, file accepts object definitions. Returns findings plus a one-line legend for the statuses that appear. Routine CONFIRMED_CWT findings are omitted. Never guarantees game correctness.',
     'inputSchema': {'type': 'object', 'properties': {'code': {'type': 'string'}, 'context': {'anyOf': [
         {'type': 'string'}, {'type': 'object', 'properties': {'type': {'type': 'string'}, 'schema': {'type': 'string'},
         'scope': {'type': 'string'}, 'mode': {'enum': ['body', 'file']}}, 'additionalProperties': False}]},
         'detail': {'type': 'boolean',
                    'description': 'Deprecated: accepted and ignored. Every call returns the one compact shape.'}},
                     'required': ['code'], 'additionalProperties': False}},
    {'name': 'stellaris_doctor',
      'description': 'Report the detected Stellaris installation and manually configured Mod directories, game version, indexed file and definition counts, generated modifiers, and source errors. Use to inspect source configuration. Read-only; add Mod folders in the GUI, repeat --mod-root, or set STELLARIS_MOD_ROOT.',
     'inputSchema': {'type': 'object', 'properties': {}, 'required': [], 'additionalProperties': False}}
]
for tool in TOOLS:
    tool['annotations'] = {'readOnlyHint': True, 'destructiveHint': False, 'idempotentHint': True, 'openWorldHint': False}

DEFAULT_SEARCH_LIMIT = 5
MAX_NAME_SEARCH_LIMIT = 10


def serialize_content(payload):
    """Expose the compact MCP projection through the universally visible text channel."""
    return json.dumps(payload, ensure_ascii=False, separators=(',', ':'))


class Server:
    def __init__(self, database=None):
        # An injected database keeps its own choice; the shipped server is created
        # by the CLI, which is where game/mod data is enabled. Tests and embedders
        # therefore stay deterministic and CWT-only by default.
        self.db = database if database is not None else Database()
        self.initialized = False

    @staticmethod
    def error(id, code, message):
        return {'jsonrpc': '2.0', 'id': id, 'error': {'code': code, 'message': message}}

    def public_metadata(self):
        upstream = self.db.upstream
        return {
            'server': {'name': 'stellaris-modder-agent-tool', 'version': __version__},
            'stellaris': {
                'version': upstream.get('stellaris_version', 'unknown'),
                'basis': upstream.get('stellaris_version_basis', 'Not declared by this corpus.'),
                'note': upstream.get('stellaris_version_note', 'CWT support is not a guarantee of complete game compatibility.'),
            },
            'cwt': {
                'repository': upstream.get('repository', 'custom'),
                'branch': upstream.get('branch'),
                'commit': upstream.get('commit_sha'),
                'packaged_date': upstream.get('packaged_date'),
                'file_count': len(self.db.documents),
            },
        }

    def search_payload(self, arguments):
        """One MCP search call: rank names, then resolve only the visible candidates."""
        arguments = dict(arguments)
        mode = arguments.pop('mode', 'name')
        limit = arguments.pop('limit', DEFAULT_SEARCH_LIMIT)
        if not isinstance(limit, int) or isinstance(limit, bool) or not 1 <= limit <= 500:
            raise ValueError('limit must be 1..500')
        if mode == 'text':
            return project('stellaris_search_text', self.db.search_text(limit=limit, **arguments))
        if limit > MAX_NAME_SEARCH_LIMIT:
            raise ValueError(f'name search limit must be 1..{MAX_NAME_SEARCH_LIMIT}')
        query = arguments.get('query')
        # stellaris_list returns exact .cwt paths. Search absorbs the old file-get
        # workflow without treating arbitrary caller text as a filesystem path.
        if isinstance(query, str) and query.strip().replace('\\', '/').casefold().endswith('.cwt'):
            return project('stellaris_get', self.db.get(query, arguments.get('type')))
        payload = self.db.search(limit=limit, **arguments)
        details = {}
        for row in payload.get('results', []):
            target = query if row.get('status') == 'TEMPLATE_MATCH' else row['name']
            key = (target, row['type'])
            if key not in details:
                details[key] = self.db.get(target, row['type'])
            row['details'] = details[key]
        return project('stellaris_search', payload)

    def legacy_get_payload(self, name, arguments):
        """Unadvertised compatibility for clients that cached the former get tool."""
        if not isinstance(arguments, dict):
            raise ValueError('Invalid tool arguments')
        arguments = {key: value for key, value in arguments.items() if key != 'detail'}
        target_key = 'name' if name == 'stellaris_get_definition' else 'target'
        if set(arguments) - {target_key, 'type'} or target_key not in arguments:
            raise ValueError('Legacy get expects ' + target_key + ' and optional type')
        if 'type' in arguments and not isinstance(arguments['type'], str):
            raise ValueError('type must be a string')
        return project('stellaris_get', self.db.get(arguments[target_key], arguments.get('type')))

    def dispatch(self, request):
        if not isinstance(request, dict) or request.get('jsonrpc') != '2.0' or not isinstance(request.get('method'), str):
            return self.error(None, -32600, 'Invalid JSON-RPC request')
        method, id = request['method'], request.get('id')
        if 'id' not in request:
            return None
        params = request.get('params', {})
        if not isinstance(params, dict):
            return self.error(id, -32602, 'params must be an object')
        if method == 'initialize':
            version = params.get('protocolVersion')
            result = {'protocolVersion': version if version in VERSIONS else VERSIONS[-1],
                      'capabilities': {'tools': {'listChanged': False}},
                      'serverInfo': {'name': 'stellaris-modder-agent-tool', 'version': __version__},
                      'instructions': INSTRUCTIONS}
            self.initialized = True
        elif method == 'ping':
            result = {}
        elif not self.initialized:
            return self.error(id, -32000, 'Initialize first')
        elif method == 'tools/list':
            result = {'tools': TOOLS}
        elif method == 'tools/call':
            name, arguments = params.get('name'), params.get('arguments', {})
            try:
                if name in ('stellaris_get', 'stellaris_get_definition'):
                    payload = self.legacy_get_payload(name, arguments)
                    result = {'content': [{'type': 'text', 'text': serialize_content(payload)}],
                              'isError': False}
                    return {'jsonrpc': '2.0', 'id': id, 'result': result}
                descriptor = next((t for t in TOOLS if t['name'] == name), None)
                if descriptor is None:
                    return self.error(id, -32602, 'Unknown tool')
                schema = descriptor['inputSchema']
                if not isinstance(arguments, dict):
                    raise ValueError('Invalid tool arguments')
                # ``detail`` used to select a richer payload. It is still accepted so that
                # already-configured clients keep working, and ignored: every tool now has
                # exactly one compact output shape.
                arguments = {key: value for key, value in arguments.items() if key != 'detail'}
                if set(arguments) - set(schema['properties']) or set(schema['required']) - set(arguments):
                    raise ValueError('Invalid tool arguments')
                if 'type' in arguments and not isinstance(arguments['type'], str):
                    raise ValueError('type must be a string')
                if 'mode' in arguments and arguments['mode'] not in ('name', 'text'):
                    raise ValueError('mode must be name or text')
                arguments = dict(arguments)
                if name == 'stellaris_search':
                    payload = self.search_payload(arguments)
                else:
                    functions = {'stellaris_list': self.db.list_files,
                                 'stellaris_doctor': self.db.doctor,
                                 'stellaris_validate': Validator(self.db).validate}
                    payload = project(name, functions[name](**arguments))
                if name == 'stellaris_list':
                    payload['metadata'] = self.public_metadata()
                result = {'content': [{'type': 'text', 'text': serialize_content(payload)}],
                          'isError': False}
            except (ValueError, TypeError, RecursionError) as error:
                result = {'content': [{'type': 'text', 'text': str(error)}], 'isError': True}
        else:
            return self.error(id, -32601, 'Method not found')
        return {'jsonrpc': '2.0', 'id': id, 'result': result}


def serve(database=None, input_stream=None, output_stream=None):
    server = Server(database)
    source = input_stream if input_stream is not None else sys.stdin.buffer
    target = output_stream if output_stream is not None else sys.stdout.buffer
    # Game/mod data is NOT indexed here on purpose. A client that spawns this
    # process reads several seconds of silence before the handshake as a dead
    # process ("Connection closed"), so the index is built on first use instead.
    # Set STELLARIS_WARMUP=1 (or call warm_game_data yourself) when a slow first
    # request is preferable to a slow start.
    if os.environ.get('STELLARIS_WARMUP', '0').strip().lower() in ('1', 'true', 'yes'):
        try:
            server.db.warm_game_data()
        except Exception as error:  # noqa: BLE001 - a cold server must still answer
            print('Game/mod data unavailable: ' + str(error), file=sys.stderr, flush=True)
    print('Stellaris MCP ready: ' + json.dumps(server.db.stats), file=sys.stderr, flush=True)
    while True:
        line = source.readline(8_000_001)
        if not line:
            break
        try:
            if len(line) > 8_000_000:
                raise ValueError('JSON-RPC message exceeds 8 MB')
            request = json.loads(line)
            response = server.dispatch(request)
        except (ValueError, UnicodeError) as error:
            response = server.error(None, -32700, str(error))
        if response is not None:
            target.write((json.dumps(response, ensure_ascii=False) + '\n').encode('utf-8'))
            target.flush()
