"""Conservative evidence validation, not an implementation of the game engine."""
from __future__ import annotations

from collections import Counter
import math
import re

from .index import Database, declaration, NOT_FOUND
from .parser import parse, ParseError, values
from .templates import Template


class Validator:
    def __init__(self, database: Database):
        self.db = database
        self.findings = []

    def emit(self, node, status, code, message, rules=(), **extra):
        row = {'status': status, 'code': code, 'identifier': node.key,
               'line': node.line, 'end_line': node.end_line, 'message': message,
               'sources': [self.db.provenance(r) for r in rules]}
        row.update(extra)
        self.findings.append(row)
        return row

    def generated_modifier(self, node, entry, scope):
        """Report one modifier generated by game/mod data, with its scopes."""
        self.emit(node, 'CONFIRMED_GAME_DATA', 'GENERATED_MODIFIER',
                  'Modifier is generated by the economic-category mechanic from game/mod data.',
                  generated_from={key: entry.get(key) for key in
                                  ('economic_category', 'resource', 'category',
                                   'modifier_type', 'triggered')},
                  source={'file': entry['path'], 'line': entry['line'],
                          'source': entry['source']})
        scopes = entry.get('supported_scopes') or []
        current = self.normal_scope(scope) if scope else None
        if scopes and current and current not in {self.normal_scope(s) for s in scopes} \
                and not set(scopes) & {'any', 'all'}:
            self.emit(node, 'UNKNOWN', 'SCOPE_MISMATCH',
                      'Modifier scope is not supported by its generated modifier categories.',
                      scope=scope, supported_scopes=sorted(set(scopes)))
        return True

    def defined_identifier(self, node, symbol):
        """Report one identifier declared by game/mod data."""
        self.emit(node, 'CONFIRMED_GAME_DATA', 'DEFINED_IN_GAME_DATA',
                  f'Identifier is defined by {symbol.origin.get("source")} data.',
                  source=dict(symbol.origin), definition_type=symbol.canonical_type)
        return True

    def dynamic_identifier(self, node, kind, scope):
        """Evidence from game/mod data for one identifier.

        Only reached when the corpus has nothing to say: bundled rules cannot declare
        mod objects, and Stellaris generates some modifier names at runtime.  Existence
        is claimed, structure is not -- bodies are deliberately left unvalidated.
        """
        if not self.db.game_data:
            return False
        registry = self.db.dynamic
        kinds = (kind,) if kind in ('trigger', 'effect', 'modifier') else ('trigger', 'effect', 'modifier')
        if 'modifier' in kinds:
            entry = registry.modifier(node.key)
            if entry is not None:
                return self.generated_modifier(node, entry, scope)
        for candidate in kinds:
            if candidate == 'modifier':
                continue
            symbol = registry.definitions_of(candidate, node.key)
            if symbol is not None:
                return self.defined_identifier(node, symbol)
        return False

    def unknown(self, node, kind, rules=()):
        candidates = []
        if rules:
            allowed = {id(r) for r in rules if not declaration(r.key)[0] and '<' not in r.key}
            for match in self.db.retrieval.find(node.key, lambda s: id(s.node) in allowed):
                if match.match_score >= 25 and match.query_support >= .2:
                    candidates.append(match.name)
        else:
            requested = kind if kind in ('trigger', 'effect', 'modifier') else None
            result = self.db.search(node.key, requested, limit=5)
            candidates.extend(row['name'] for row in result.get('results', []))
            candidates.extend(row['name'] for row in result.get('related', []))
        candidates = list(dict.fromkeys(candidates))[:5]
        self.emit(node, 'UNKNOWN', 'UNKNOWN_' + kind.upper(), NOT_FOUND,
                  suggestions=[{'status': 'SUGGESTION', 'name': n} for n in candidates])
        self.unchecked(node.children or [], 'Parent identifier has no resolved CWT rule.')

    def unchecked(self, nodes, message):
        for node in nodes:
            self.emit(node, 'UNRESOLVED', 'UNRESOLVED_CONTEXT', message)
            self.unchecked(node.children or [], message)

    def normal_scope(self, scope):
        return self.db.scope_aliases.get(scope.casefold(), scope.casefold()) if scope else None

    def scope_check(self, node, rules, scope):
        constraints = [self.db.annotations(r, 'scopes') or self.db.annotations(r, 'scope') for r in rules]
        if not any(constraints):
            return
        if not scope:
            self.emit(node, 'UNRESOLVED', 'SCOPE_CONTEXT_REQUIRED', 'CWT restricts scopes; current scope was not supplied.', rules)
            return
        allowed = {self.normal_scope(s) for group in constraints for s in group}
        current = self.normal_scope(scope)
        ancestors = {current}
        while current in self.db.scope_parents and self.db.scope_parents[current] not in ancestors:
            current = self.normal_scope(self.db.scope_parents[current])
            ancestors.add(current)
        if not (ancestors & allowed or allowed & {'any', 'all'}):
            status = 'UNRESOLVED' if any(not c for c in constraints) else 'UNKNOWN'
            self.emit(node, status, 'SCOPE_MISMATCH', 'Current scope is not supported by the resolved CWT scope constraints.',
                      rules, scope=scope, supported_scopes=sorted(allowed))

    def next_scope(self, rules, scope):
        pushed = set()
        for rule in rules:
            pushed.update(self.db.annotations(rule, 'push_scope'))
            for meta in self.db.meta.get(id(rule), []):
                if meta.key in ('replace_scopes', 'replace_scope') and meta.children:
                    this = meta.field('this')
                    if this:
                        pushed.add(this.value)
        return next(iter(pushed)) if len(pushed) == 1 else (None if pushed else scope)

    def expand(self, rules, seen=None):
        """Return (field rule, conditional) entries plus unresolved constructs."""
        seen = set() if seen is None else seen
        entries, unresolved = [], []
        for rule in rules:
            if id(rule) in seen:
                unresolved.append(('CYCLIC_CWT_REFERENCE', rule))
                continue
            trail = seen | {id(rule)}
            if rule.children is not None:
                for child in rule.children:
                    decl, _ = declaration(child.key)
                    if decl == 'subtype':
                        nested, issues = self.expand([child], trail)
                        entries.extend((n, True) for n, _ in nested)
                        unresolved.extend(issues)
                    else:
                        entries.append((child, False))
            else:
                decl, name = declaration(rule.value or '')
                targets = self.db.singles.get(name, []) if decl == 'single_alias_right' else self.db.schemas.get(rule.value, [])
                if targets:
                    nested, issues = self.expand(targets, trail)
                    entries.extend(nested)
                    unresolved.extend(issues)
                else:
                    unresolved.append(('UNSUPPORTED_BLOCK_RULE', rule))
            for injection in self.db.annotations(rule, 'inject'):
                file, sep, path = injection.partition('@')
                parts = path.split('/')
                targets = self.db.documents[file].nodes if sep and file in self.db.documents else []
                for index, part in enumerate(parts[:-1]):
                    targets = [n for n in targets if n.key == part]
                    if index < len(parts)-2:
                        targets = [c for n in targets for c in n.children or []]
                if targets and parts[-1] == '*':
                    nested, issues = self.expand(targets, trail)
                    entries.extend(nested)
                    unresolved.extend(issues)
                else:
                    unresolved.append(('UNRESOLVED_INJECTION', rule))
        return entries, unresolved

    def scalar(self, rule, value):
        """yes/no/unknown: enough to select overloads without guessing."""
        expected = rule.value if rule.operator else rule.key
        if expected is None:
            return 'no', 'block expected'
        if rule.value_quoted:
            return ('yes', '') if value == expected else ('no', 'literal differs')
        if expected == 'bool':
            return ('yes', '') if value in ('yes', 'no') else ('no', 'expected yes or no')
        if expected in ('scalar', 'string'):
            return 'yes', ''
        numeric = re.fullmatch(r'(int|float)(?:([\[(])([^\s]+)\.\.([^\s]+)([\])]))?', expected)
        if numeric or expected in ('value_field', 'int_value_field'):
            try:
                number = float(value)
                if not math.isfinite(number):
                    return 'no', 'finite number required'
                integer = expected.startswith('int')
                if integer and not re.fullmatch(r'[+-]?\d+', value):
                    return 'no', 'integer required'
                if numeric and numeric.group(2):
                    low, high = float(numeric.group(3)), float(numeric.group(4))
                    if number < low or number > high or (number == low and numeric.group(2) == '(') or (number == high and numeric.group(5) == ')'):
                        return 'no', 'outside CWT numeric range'
                return 'yes', ''
            except ValueError:
                return ('unknown', 'variable/expression requires game or mod definitions') if expected.endswith('value_field') or value.startswith('@') else ('no', 'number required')
        decl, name = declaration(expected)
        if decl == 'complex_enum':
            # ``complex_enum[x]`` deliberately ships an empty ``enum_name = { }``: its
            # members are harvested by the game from the definitions in ``path`` (for
            # example ``section_slot`` is read from common/ship_sizes).  The corpus holds
            # no member list, so the value can be neither confirmed nor denied here; it
            # must never be compared as if ``complex_enum[x]`` were the expected literal.
            return 'unknown', 'complex_enum[' + name + '] values come from game/mod definitions'
        if decl == 'enum':
            enums = self.db.enums.get(name, [])
            if enums:
                members = [n.key for e in enums for n in e.children or []]
                if value in members:
                    return 'yes', ''
                if members and all(not declaration(m)[0] and '<' not in m for m in members):
                    return 'no', 'not a member of enum[' + name + ']'
            if self.db.game_data and name in self.db.complex_enums:
                result = self.db.dynamic.verify_enum(name, value)
                if result.get('object_existence') == 'CONFIRMED':
                    return 'yes', ''
                if result.get('object_existence') == 'NOT_FOUND':
                    return 'no', 'not a member of complex_enum[' + name + ']'
            return 'unknown', 'enum requires external/dynamic values'
        if decl or '<' in expected or expected.startswith('$') or expected in (
                'localisation', 'synced_localisation', 'inline_localisation', 'scope_field', 'percentage_field',
                'variable_field', 'int_variable_field', 'date_field', 'color_field', 'country_tag'):
            return 'unknown', 'reference or semantic value requires additional data'
        if expected in self.db.schemas:
            return 'no', 'block expected'
        # Recognized literals are evidence only for exactly that spelling.
        if re.fullmatch(r'[\w.:-]+', expected):
            return ('yes', '') if value == expected else ('no', 'CWT literal differs')
        return 'unknown', 'uninterpreted CWT value construct'

    def object_reference(self, node, rules, value, scope):
        """Resolve literal ``<type>`` values against the loaded game/mod objects."""
        if not self.db.game_data or not isinstance(value, str):
            return False
        if not re.fullmatch(r'[A-Za-z_][\w.:-]*', value) \
                or value.startswith(('event_target:', 'parameter:')):
            return False
        checks = []
        for rule in rules:
            expected = rule.value if rule.operator else rule.key
            match = re.fullmatch(r'<([A-Za-z_][A-Za-z0-9_.]*)>', expected or '')
            if not match:
                continue
            checks.append((rule, self.db.dynamic.verify_reference(expected, value)))
        if not checks:
            return False
        confirmed = [(rule, result) for rule, result in checks
                     if result.get('object_existence') == 'CONFIRMED']
        if confirmed:
            rule, result = confirmed[0]
            self.emit(node, 'CONFIRMED_GAME_DATA', 'OBJECT_REFERENCE',
                      f'Referenced {result.get("object_type")} exists in loaded game/mod data.',
                      [rule], object_type=result.get('object_type'),
                      source=result.get('resolved_from'))
            self.scope_check(node, [rule], scope)
            return True
        if len(checks) == len(rules) and all(result.get('object_existence') == 'NOT_FOUND'
                                             for _, result in checks):
            object_types = list(dict.fromkeys(result.get('object_type') for _, result in checks
                                               if result.get('object_type')))
            candidates = list(dict.fromkeys(candidate for _, result in checks
                                             for candidate in result.get('candidates', ())))[:5]
            label = '/'.join(object_types) or 'object'
            self.emit(node, 'UNKNOWN', 'UNKNOWN_OBJECT_REFERENCE',
                      f'No {label} named {value} exists in the loaded game/mod data.',
                      [rule for rule, _ in checks], object_type=label, candidates=candidates)
            return True
        return False

    def supports_block(self, rule):
        decl, name = declaration(rule.value or '')
        return rule.children is not None or decl == 'single_alias_right' or rule.value in self.db.schemas

    def check_rule(self, node, rules, scope, evidence='CONFIRMED_CWT', conditional=False, depth=0):
        if depth > 80:
            self.emit(node, 'UNRESOLVED', 'DEPTH_LIMIT', 'Semantic recursion limit reached.', rules)
            self.unchecked(node.children or [], 'Depth limit reached.')
            return
        is_block = node.children is not None
        shaped = [r for r in rules if self.supports_block(r) == is_block]
        if not shaped:
            self.emit(node, 'UNKNOWN', 'SHAPE_MISMATCH', 'CWT expects a different scalar/block shape.', rules)
            self.unchecked(node.children or [], 'Shape does not match CWT.')
            return
        # CWT == denotes a comparison-capable rule, not just a literal == token.
        legal = [r for r in shaped if r.operator is None or
                 (node.operator in ('=', '==', '!=', '<', '>', '<=', '>=') if r.operator == '==' else node.operator == r.operator)]
        if not legal:
            self.emit(node, 'UNKNOWN', 'OPERATOR_MISMATCH', 'Operator has no matching CWT rule.', shaped)
            self.unchecked(node.children or [], 'Operator mismatch.')
            return
        rules = legal
        for rule in rules:
            unsupported = [m.key for m in self.db.meta.get(id(rule), [])
                           if m.key in ('__unparsed_metadata__', 'cardinality_max_define', 'modifier_categories')]
            if unsupported:
                self.emit(node, 'UNRESOLVED', 'UNSUPPORTED_CWT_CONSTRAINT',
                          'Additional CWT constraint requires semantics not implemented here: ' + ', '.join(unsupported), [rule])
        if not is_block:
            outcomes = [(r, *self.scalar(r, node.value if node.operator else node.key)) for r in rules]
            accepted = [r for r, state, _ in outcomes if state == 'yes']
            maybe = [r for r, state, _ in outcomes if state == 'unknown']
            if not accepted and maybe and self.object_reference(
                    node, maybe, node.value if node.operator else node.key, scope):
                return
            if not accepted and not maybe:
                self.emit(node, 'UNKNOWN', 'VALUE_MISMATCH', '; '.join(sorted(set(reason for _, _, reason in outcomes))), rules,
                          expected=[r.value if r.operator else r.key for r in rules])
                return
            rules = accepted or maybe
            self.emit(node, 'UNRESOLVED' if conditional else evidence,
                      'CONDITIONAL_SCHEMA' if conditional else 'CWT_IDENTIFIER',
                      'Field depends on a CWT subtype condition.' if conditional else 'Identifier has CWT evidence.', rules)
            if not accepted:
                self.emit(node, 'UNRESOLVED', 'VALUE_REFERENCE_UNRESOLVED',
                          'CWT reference exists; target object/value is not established by this corpus.', rules)
            self.scope_check(node, rules, scope)
            return
        self.emit(node, 'UNRESOLVED' if conditional else evidence,
                  'CONDITIONAL_SCHEMA' if conditional else 'CWT_IDENTIFIER',
                  'Subtype conditions have not been resolved.' if conditional else 'Block has CWT evidence.', rules)
        if len(rules) > 1 and len({r.raw.split('=', 1)[-1].strip() for r in rules}) > 1:
            self.emit(node, 'UNRESOLVED', 'AMBIGUOUS_OVERLOAD',
                      'Multiple block overloads apply; fields are checked against their union, not a proven single overload.', rules)
        self.scope_check(node, rules, scope)
        next_scope = self.next_scope(rules, scope)
        entries, issues = self.expand(rules)
        for code, rule in issues:
            self.emit(node, 'UNRESOLVED', code, 'CWT construct retained but not completely resolved.', [rule])
        self.fields(node.children, entries, next_scope, depth+1, bool(issues), anchor=node)

    def fields(self, nodes, entries, scope, depth=0, incomplete=False, anchor=None):
        rules = [r for r, _ in entries]
        alias_kinds = [declaration(r.key)[1] for r in rules if declaration(r.key)[0] == 'alias_name']
        for node in nodes:
            if node.key.startswith('@'):
                self.emit(node, 'UNRESOLVED', 'SCRIPT_VARIABLE', 'Script variables require value resolution.')
                self.unchecked(node.children or [], 'Script variable block is unresolved.')
                continue
            exact = [(r, conditional) for r, conditional in entries if r.key.casefold() == node.key.casefold()
                     and (r.operator is None) == (node.operator is None)]
            if exact:
                self.check_rule(node, [r for r, _ in exact], scope, conditional=all(c for _, c in exact), depth=depth)
                continue
            found = []
            for kind in alias_kinds:
                found.extend((s, status, captures) for s, status, captures in self.db.lookup(node.key, ('kind', kind)))
            if found:
                kinds = {s.kind for s, _, _ in found}
                if len(kinds) > 1:
                    self.emit(node, 'UNRESOLVED', 'AMBIGUOUS_CONTEXT', 'Multiple CWT alias contexts match.', [s.node for s, _, _ in found])
                    self.unchecked(node.children or [], 'Ambiguous alias context.')
                else:
                    self.api(node, next(iter(kinds)), scope, depth)
                continue
            if alias_kinds and node.children is not None and self.link(node, alias_kinds, scope, depth):
                continue
            dynamic = []
            for rule, conditional in entries:
                if declaration(rule.key)[0] in ('alias_name', 'subtype'):
                    continue
                if (rule.operator is None) != (node.operator is None):
                    continue
                if Template(rule.key).exact(node.key) is not None:
                    dynamic.append((rule, conditional, 'TEMPLATE_MATCH'))
                elif re.fullmatch(r'<[^<>]+>', rule.key) or rule.key.startswith('$'):
                    dynamic.append((rule, conditional, 'TEMPLATE_MATCH'))
                elif rule.key in ('scalar', 'int', 'float') or declaration(rule.key)[0] in ('enum', 'value', 'value_set'):
                    proxy = type('Rule', (), {'value': rule.key, 'operator': '=', 'value_quoted': False})()
                    state, _ = self.scalar(proxy, node.key)
                    if state != 'no':
                        dynamic.append((rule, conditional, 'TEMPLATE_MATCH' if state == 'unknown' else 'CONFIRMED_CWT'))
            if dynamic:
                self.check_rule(node, [r for r, _, _ in dynamic], scope, dynamic[0][2], all(c for _, c, _ in dynamic), depth)
            elif incomplete:
                self.emit(node, 'UNRESOLVED', 'INCOMPLETE_SCHEMA', 'Schema expansion is incomplete; cannot classify this field.', rules)
                self.unchecked(node.children or [], 'Incomplete parent schema.')
            elif self.dynamic_identifier(node, alias_kinds[0] if len(alias_kinds) == 1 else 'identifier', scope):
                # The corpus has nothing to say, but the loaded game/mod data declares this
                # name. Without this check a mod's own scripted effect was reported as
                # UNKNOWN_EFFECT *and* listed among its own suggestions, because this
                # dispatch path never consulted the data the way ``api`` does.
                pass
            else:
                self.unknown(node, alias_kinds[0] if len(alias_kinds) == 1 else 'schema_field', rules if not alias_kinds else ())
        # Check explicit cardinality only; conditional/overloaded and approximate
        # (~) constraints are not treated as unconditional requirements.
        counts = Counter(n.key.casefold() for n in nodes)
        groups = {}
        for rule, conditional in entries:
            if not conditional and not declaration(rule.key)[0] and '<' not in rule.key and rule.operator:
                groups.setdefault(rule.key.casefold(), []).append(rule)
        for key, group in groups.items():
            ranges = [self.db.annotations(r, 'cardinality') for r in group]
            if not ranges or not all(len(x) == 1 and re.fullmatch(r'\d+\.\.(\d+|inf)', x[0]) for x in ranges):
                continue
            lower = min(int(x[0].split('..')[0]) for x in ranges)
            upper = max(float(x[0].split('..')[1]) for x in ranges)
            if not lower <= counts[key] <= upper:
                # A missing field has no node of its own: its absence belongs to the block
                # that should have declared it. Falling back to an arbitrary sibling (the
                # old ``nodes[0]``) blamed whatever child happened to come first, which
                # sent the reader to the wrong place entirely.
                location = next((n for n in nodes if n.key.casefold() == key), None) \
                    or (anchor if anchor is not None else (nodes[0] if nodes else None))
                if location:
                    expected = '%d..%d' % (lower, int(upper)) if upper != float('inf') \
                        else '%d..inf' % lower
                    self.emit(location, 'UNKNOWN', 'CARDINALITY_MISMATCH',
                              f'{key}: count {counts[key]}, expected {expected}.', group,
                              field=key, expected=expected)

    def link(self, node, kinds, scope, depth):
        rules = self.db.links.get(node.key.casefold(), [])
        if not rules:
            if node.key.casefold() in ('root', 'prev', 'this', 'from') or node.key.startswith(('event_target:', 'parameter:')) or '.' in node.key:
                self.emit(node, 'UNRESOLVED', 'DYNAMIC_SCOPE', 'Dynamic/chained scope needs runtime scope context.')
                self.fields(node.children or [], [(r, False) for k in kinds for r in self.alias_entries(k)], None, depth+1)
                return True
            return False
        self.emit(node, 'CONFIRMED_CWT', 'CWT_SCOPE_LINK', 'Scope link is explicitly defined.', rules)
        allowed = {self.normal_scope(s) for r in rules for s in values(r.field('input_scopes'))}
        if scope and self.normal_scope(scope) not in allowed and not allowed & {'any', 'all'}:
            self.emit(node, 'UNKNOWN', 'SCOPE_MISMATCH', 'Scope link input scope does not match.', rules,
                      scope=scope, supported_scopes=sorted(allowed))
        elif not scope:
            self.emit(node, 'UNRESOLVED', 'SCOPE_CONTEXT_REQUIRED', 'Scope link input cannot be checked without current scope.', rules)
        outputs = {r.field('output_scope').value for r in rules if r.field('output_scope')}
        self.fields(node.children, [(r, False) for k in kinds for r in self.alias_entries(k)],
                    next(iter(outputs)) if len(outputs) == 1 else None, depth+1)
        return True

    def alias_entries(self, kind):
        single = self.db.singles.get(kind + '_clause', [])
        return [n for r in single for n in r.children or []]

    def api(self, node, kind, scope, depth=0):
        if node.key == 'scope_field' or '<' in node.key or '[' in node.key:
            self.emit(node, 'UNRESOLVED', 'CWT_METASYNTAX', 'CWT placeholder/metasyntax is not a concrete game identifier.')
            self.unchecked(node.children or [], 'Concrete identifier needed.')
            return
        matches = self.db.lookup(node.key, ('kind', kind), dynamic=True)
        # Game/mod data is evidence of its own kind: it confirms the identifier but
        # never pretends to be a CWT declaration, so it is reported separately.
        if matches and all(self.db.is_dynamic(symbol) for symbol, _, _ in matches):
            symbol = matches[0][0]
            if symbol.generated is not None:
                return self.generated_modifier(node, symbol.generated, scope)
            return self.defined_identifier(node, symbol)
        if not matches:
            if node.children is not None and self.link(node, [kind], scope, depth):
                return
            if self.dynamic_identifier(node, kind, scope):
                return
            self.unknown(node, kind)
            return
        if kind == 'modifier':
            missing = [capture for _, _, captures in matches if captures for capture in captures
                       if capture.get('object_existence') == 'NOT_FOUND']
            if missing:
                # Structure matched a documented template, but the substituted object
                # does not exist in the loaded game/mod data.
                self.emit(node, 'UNKNOWN', 'UNKNOWN_MODIFIER',
                          'Template structure matches, but the referenced game/mod object was not found: '
                          + str(missing[0].get('object_note') or missing[0].get('value')) + '.',
                          [s.node for s, _, _ in matches if s.node is not None], substitutions=missing)
                return
            declarations = [s for s, _, _ in matches if self.db.modifier_scopes(s) is not None]
            if declarations:
                self.emit(node, matches[0][1], 'CWT_IDENTIFIER', 'Modifier name has CWT evidence.', [s.node for s in declarations])
                for symbol in declarations:
                    resolved = self.db.modifier_scopes(symbol)
                    if resolved['status'] == 'UNRESOLVED':
                        self.emit(node, 'UNRESOLVED', 'UNRESOLVED_MODIFIER_CATEGORY', 'Modifier category cannot be resolved.', [symbol.node], scope_resolution=resolved)
                    elif scope and self.normal_scope(scope) not in {self.normal_scope(x) for x in resolved['supported_scopes']} and not set(resolved['supported_scopes']) & {'any', 'all'}:
                        self.emit(node, 'UNKNOWN' if resolved['supported_scopes'] else 'UNRESOLVED', 'SCOPE_MISMATCH', 'Modifier scope is not supported by its CWT categories.', [symbol.node], scope_resolution=resolved)
                # Numeric RHS is supplied by alias[modifier:<modifier>], not the category block.
                value_rules = [s.node for s in self.db.aliases['modifier'] if s.name == '<modifier>']
                if value_rules:
                    self.check_rule(node, value_rules, None, matches[0][1], depth=depth)
                else:
                    self.emit(node, 'UNRESOLVED', 'MODIFIER_VALUE_RULE_MISSING', 'No generic modifier value rule exists in this corpus.')
                return
        self.check_rule(node, [s.node for s, _, _ in matches], scope, matches[0][1], depth=depth)

    def validate(self, code, context=None):
        self.findings = []
        if not isinstance(code, str) or len(code) > 2_000_000:
            raise ValueError('code must be a string, at most 2,000,000 characters')
        if isinstance(context, str):
            # Common registry kinds and real CWT paths keep their long-standing type
            # meaning.  A bare known schema with no type/path interpretation is the
            # intuitive shorthand for {"schema": ...}; in particular this makes
            # ``scripted_effect`` consistent with search's accepted spelling.
            _, type_error = self.db.resolve_type(context)
            context = ({'schema': context} if context in self.db.schemas and type_error
                       else {'type': context})
        if context is not None and not isinstance(context, dict):
            raise ValueError('context must be a type string or an object')
        ctx = context or {}
        unexpected = set(ctx) - {'type', 'schema', 'scope', 'mode'}
        if unexpected:
            raise ValueError('Unknown context fields: ' + ', '.join(sorted(unexpected)))
        if any(not isinstance(v, str) for v in ctx.values()) or ctx.get('mode', 'body') not in ('body', 'file'):
            raise ValueError('context values must be strings; mode is body or file')
        try:
            doc = parse(code, '<script>')
        except (ParseError, RecursionError) as error:
            return {'status': 'UNKNOWN', 'findings': [{'status': 'UNKNOWN', 'code': 'SCRIPT_PARSE_ERROR', 'message': str(error)}],
                    'game_correctness': 'NOT_EVALUATED'}
        selected, error = self.db.resolve_type(ctx.get('type'))
        if error:
            return {**error, 'game_correctness': 'NOT_EVALUATED'}
        scope = ctx.get('scope')
        if scope and self.normal_scope(scope) not in set(self.db.scope_aliases.values()) | {'any', 'all'}:
            return {'status': 'UNRESOLVED', 'code': 'UNKNOWN_SCOPE_CONTEXT', 'scope': scope,
                    'game_correctness': 'NOT_EVALUATED'}
        if selected and selected[0] == 'kind':
            for node in doc.nodes:
                self.api(node, selected[1], scope)
        elif selected or ctx.get('schema'):
            schemas = [n for name, nodes in self.db.schemas.items() if name in self.db.types
                       for n in nodes if not selected or n.document.path[:-4] == selected[1]]
            if ctx.get('schema'):
                schemas = [n for n in self.db.schemas.get(ctx['schema'], [])
                           if not selected or n.document.path[:-4] == selected[1]]
            if len(schemas) != 1:
                if doc.nodes:
                    self.emit(doc.nodes[0], 'UNRESOLVED', 'AMBIGUOUS_CONTEXT', 'Specify context.schema to choose a root schema.', schemas,
                              candidates=sorted(set(n.key for n in schemas)))
                self.unchecked(doc.nodes, 'Root schema has not been uniquely selected.')
            elif ctx.get('mode') == 'file':
                for node in doc.nodes:
                    if node.children is None:
                        self.emit(node, 'UNRESOLVED', 'FILE_LEVEL_DIRECTIVE', 'File-level scalar/directive is outside the selected object schema.')
                        continue
                    object_scope = scope
                    filters = []
                    for typedef in self.db.types.get(schemas[0].key, []):
                        filters.extend(self.db.annotations(typedef, 'type_key_filter'))
                        for subtype in typedef.children or []:
                            choices = self.db.annotations(subtype, 'type_key_filter')
                            filters.extend(choices)
                            if node.key in choices:
                                object_scope = self.next_scope([subtype], scope)
                    if filters and node.key not in filters:
                        self.emit(node, 'UNRESOLVED', 'ROOT_KEY_FILTER', 'Root key does not match resolved type filters; negation/complex filters may need CWTools.', schemas)
                    self.check_rule(node, schemas, object_scope,
                                    'CONFIRMED_CWT' if node.key in filters else 'TEMPLATE_MATCH')
            else:
                entries, issues = self.expand(schemas)
                for issue, rule in issues:
                    if doc.nodes:
                        self.emit(doc.nodes[0], 'UNRESOLVED', issue, 'Root schema expansion incomplete.', [rule])
                self.fields(doc.nodes, entries, self.next_scope(schemas, scope), incomplete=bool(issues))
        else:
            for node in doc.nodes:
                matches = self.db.lookup(node.key)
                kinds = {s.kind for s, _, _ in matches if s.kind in ('trigger', 'effect', 'modifier')}
                if len(kinds) == 1:
                    self.api(node, next(iter(kinds)), scope)
                elif not matches:
                    if not self.dynamic_identifier(node, 'identifier', scope):
                        self.unknown(node, 'identifier')
                else:
                    self.emit(node, 'UNRESOLVED', 'AMBIGUOUS_CONTEXT', 'Specify trigger/effect/modifier or a schema context.', [s.node for s, _, _ in matches])
                    self.unchecked(node.children or [], 'Ambiguous parent context.')
        counts = Counter(f['status'] for f in self.findings)
        status = next((s for s in ('UNKNOWN', 'UNRESOLVED', 'TEMPLATE_MATCH', 'CONFIRMED_GAME_DATA')
                       if counts[s]), 'CONFIRMED_CWT')
        if not doc.nodes:
            status = 'UNRESOLVED'
        built = self.db.dynamic.built
        note = 'Validation reports support in bundled CWT, not guaranteed game correctness.'
        if built:
            note += ' Game/mod data is loaded: object existence is verified against real declarations.'
        return {'status': status, 'context': ctx, 'findings': self.findings, 'counts': dict(counts),
                'game_correctness': 'NOT_EVALUATED', 'dataset': self.db.dataset,
                'coverage': {'syntax': True, 'identifier_evidence': True, 'nested_aliases': True,
                             'explicit_cardinality': True, 'static_scope_constraints': True,
                             'runtime_objects': built, 'full_cwtools_semantics': False,
                             'subtype_conditions': 'Reported as UNRESOLVED when a field depends on them.'},
                'note': note}
