"""Game/mod data backed names: the dynamic half of the corpus.

The bundled CWT corpus declares *shapes* (``job_<job>_add``,
``<economic_category>_<resource>_produces_mult``) but cannot know the concrete
objects, because they live in game data.  This module loads both data sources and
turns those shapes into names that can actually be confirmed:

* ``ParadoxTemplate``-style placeholders are resolved against indexed definitions,
  so ``job_researcher_add`` is only confirmed when ``researcher`` really is a job.
* Stellaris economic-category modifiers are *generated* from the declarations in
  ``common/economic_categories`` -- the same algorithm the reference implementation
  uses -- instead of being guessed from a regular expression.
* Definitions written by the user's own mod are exposed as first-class symbols, so
  a scripted trigger declared in the mod resolves instead of reporting UNKNOWN.

Nothing here is required: when the game cannot be found the registry stays disabled
and every caller keeps the previous CWT-only behaviour.
"""
from __future__ import annotations

from dataclasses import dataclass, field as dataclass_field
import difflib
from pathlib import Path
import time

from . import environment as environment_module
from . import gamedata
from .templates import Template

CATEGORIES_ENUM = 'economic_modifier_category'
TYPES_ENUM = 'economic_modifier_type'
DEFAULT_MODIFIER_CATEGORY = 'economic_unit'
EXTRA_TYPES = ('economic_category', 'resource', 'scripted_trigger', 'scripted_effect')
TRIGGERED_MEMBERS = (
    ('triggered_cost_modifier', 'cost'),
    ('triggered_produces_modifier', 'produces'),
    ('triggered_upkeep_modifier', 'upkeep'),
    ('triggered_logistics_modifier', 'logistics'),
)
MAX_GENERATED = 200000
KIND_BY_TYPE = {'scripted_trigger': 'trigger', 'scripted_effect': 'effect'}
DERIVED_PLACEHOLDER = '<economic_category>[_<resource>]'


@dataclass
class DynamicSymbol:
    """Quacks like ``index.Symbol`` for the CWT-only readers that consume it."""

    name: str
    kind: str
    canonical_type: str
    path: str
    id: str
    origin: dict = dataclass_field(default_factory=dict)
    definition: gamedata.Definition | None = None
    generated: dict | None = None
    node: None = None
    template: Template | None = None
    derived_rule: None = None
    derived_definition: None = None
    derived_source_line: None = None
    dynamic: bool = True

    def __post_init__(self):
        if self.template is None:
            self.template = Template(self.name)

    def defined_text(self):
        """Definition text plus its location, mirroring ``Database.source``."""
        if self.definition is not None:
            text = self.definition.read_text()
            return {'text': text, 'start_line': self.definition.line,
                    'end_line': self.definition.line + text.count('\n')}
        if self.generated is not None:
            entry = self.generated
            lines = [f'# Generated by the economic-category mechanic of Stellaris.',
                     f'# economic_category = {entry["economic_category"]}'
                     + (f', resource = {entry["resource"]}' if entry.get('resource') else '')
                     + f', {entry["category"]} x {entry["modifier_type"]}'
                     + (' (triggered declaration)' if entry.get('triggered') else '') + '.',
                     f'{self.name} = {{ {" ".join(entry.get("supported_scopes") or [])} }}']
            return {'text': '\n'.join(lines), 'start_line': entry.get('line'), 'end_line': entry.get('line')}
        return {'text': '', 'start_line': None, 'end_line': None}


def _enum_values(db, name):
    result = []
    for node in db.enums.get(name, []):
        result.extend(values_like(node))
    return [value.casefold() for value in result if value]


def values_like(node):
    """Bare members of an enum block, tolerant of both parser shapes."""
    result = []
    for child in node.children or []:
        if child.children is None and child.key:
            result.append(child.key)
    return result


def _normalise(values):
    return [value.casefold() for value in values or () if value]


class DynamicRegistry:
    """Lazily built view over the game and mod data sources."""

    def __init__(self, db, environment=None, index=None, available=True, watch=True, interval=2.0):
        self.db = db
        self.environment = environment
        self.available = bool(available)
        self.watch = bool(watch) and self.available
        self.interval = float(interval)
        self._index = index
        self._modifiers = None
        self._all_symbols = None
        self._build_error = None
        self._seconds = None
        self._truncated = False
        self._types = None
        self._reference_indexes = {}
        self._call_index = None
        self._localisation = None
        self._fingerprint = None
        self._last_check = 0.0
        self._refreshes = 0

    # region construction

    def _ensure(self):
        if self._index is not None or self._build_error is not None:
            return
        if not self.available:
            self._build_error = 'Game/mod data is disabled; pass game_data=True to enable it.'
            return
        started = time.perf_counter()
        try:
            environment = self.environment
            if environment is None:
                environment = environment_module.detect_environment()
                self.environment = environment
            if not environment.entries():
                self._build_error = 'No game or mod data source was detected.'
                return
            types = gamedata.needed_types(self.db, extra=EXTRA_TYPES)
            self._types = types
            self._index = gamedata.build_index(self.db, environment, types=types)
            self._fingerprint = tuple(self._index.stats.get('fingerprint') or ())
            self._last_check = time.monotonic()
        except Exception as error:  # noqa: BLE001 - a broken data source never breaks the server
            self._build_error = f'{type(error).__name__}: {error}'
        finally:
            self._seconds = round(time.perf_counter() - started, 3)

    def refresh_if_stale(self, force=False):
        """Rebuild the snapshot when the game/mod files changed.

        Modding is iterative: a new scripted trigger has to become visible without
        restarting the server.  The check is a directory walk (no parsing) and is
        throttled, so a burst of requests pays it at most once per interval.
        """
        if not self.watch or self._index is None:
            return False
        now = time.monotonic()
        if not force and now - self._last_check < self.interval:
            return False
        self._last_check = now
        try:
            watched = set(self._types or ()) | set(self._reference_indexes)
            current = tuple(gamedata.fingerprint(self.db, self.environment, watched))
        except Exception:  # noqa: BLE001 - a failed check must never break a request
            return False
        if current == self._fingerprint:
            return False
        reference_types = set(self._reference_indexes)
        self._index = None
        self._reference_indexes = {}
        self._modifiers = None
        self._all_symbols = None
        self._localisation = None
        self._build_error = None
        self._call_index = None
        self._ensure()
        for type_name in reference_types:
            self._reference_index(type_name)
        self._refreshes += 1
        return True

    @property
    def index(self):
        self._ensure()
        return self._index

    @property
    def enabled(self):
        return self.index is not None

    @property
    def built(self):
        """Whether the index was already built, without forcing the lazy build."""
        return self._index is not None

    @property
    def reason(self):
        self._ensure()
        return self._build_error

    # endregion

    # region generated modifiers

    def modifiers(self):
        """Concrete modifier names generated by the economic-category mechanic."""
        if self._modifiers is None:
            self._modifiers = self._generate()
        return self._modifiers

    def _generate(self):
        index = self.index
        if index is None or not index.has_type('economic_category'):
            return {}
        resources = index.names('resource')
        categories = _enum_values(self.db, CATEGORIES_ENUM)
        types = _enum_values(self.db, TYPES_ENUM)
        result = {}
        for category_name in index.names('economic_category'):
            definition = index.get('economic_category', category_name)
            data = definition.data or {}
            generate_add = set(_normalise(data.get('generate_add_modifiers')))
            generate_mult = set(_normalise(data.get('generate_mult_modifiers')))
            triggered = [(member, fixed) for member, fixed in TRIGGERED_MEMBERS]
            for resource in list(resources) + [None]:
                for category in categories:
                    if category in generate_add:
                        self._add(result, category_name, resource, category, 'add', definition, False)
                    if category in generate_mult:
                        self._add(result, category_name, resource, category, 'mult', definition, False)
                for member, fixed in triggered:
                    for block in data.get(member) or ():
                        allowed = set(_normalise(block.get('modifier_types')))
                        for modifier_type in types:
                            if modifier_type in allowed:
                                self._add(result, block['key'], resource, fixed, modifier_type,
                                          definition, True, block.get('use_parent_icon'))
            if len(result) >= MAX_GENERATED:
                self._truncated = True
                break
        return result

    def _add(self, result, key, resource, category, modifier_type, definition, triggered, use_parent_icon=None):
        if not key:
            return
        # Resource-less declarations only exist for `_mult` (upstream rule).
        if resource is None and modifier_type != 'mult':
            return
        name = (f'{key}_{resource}_{category}_{modifier_type}' if resource
                else f'{key}_{category}_{modifier_type}')
        if name in result:
            return
        result[name] = {
            'name': name, 'economic_category': definition.name, 'resource': resource,
            'category': category, 'modifier_type': modifier_type, 'triggered': triggered,
            'use_parent_icon': use_parent_icon, 'source': definition.source,
            'path': definition.rel_path, 'line': definition.line,
            'modifier_category': (definition.data or {}).get('modifier_category', DEFAULT_MODIFIER_CATEGORY),
            'supported_scopes': self.modifier_scopes(
                (definition.data or {}).get('modifier_category', DEFAULT_MODIFIER_CATEGORY)),
        }

    def modifier_scopes(self, modifier_category):
        """Supported scopes of a modifier category, falling back to economic_unit.

        Category keys are compared loosely: the game writes ``economic_unit`` while
        the corpus may spell the same category ``Economic Units``.
        """
        for candidate in (modifier_category, DEFAULT_MODIFIER_CATEGORY):
            if not candidate:
                continue
            nodes = self._category_nodes(candidate)
            scopes = []
            for node in nodes:
                scopes.extend(value for value in _block_values(node, 'supported_scopes'))
            if scopes:
                return list(dict.fromkeys(scopes))
        return []

    def _category_nodes(self, name):
        folded = name.casefold().strip()
        nodes = self.db.categories.get(folded, [])
        if nodes:
            return nodes
        squashed = folded.replace('_', ' ')
        for key, candidates in self.db.categories.items():
            published = key.replace('_', ' ')
            if published == squashed or published.rstrip('s') == squashed.rstrip('s'):
                return candidates
        return []

    def modifier(self, name):
        if not name:
            return None
        return self.modifiers().get(name)

    # endregion

    # region symbols

    def symbol_for_modifier(self, name):
        entry = self.modifier(name)
        if entry is None:
            return None
        return DynamicSymbol(
            name=name, kind='modifier', canonical_type='modifier',
            path=entry['path'], id=f'generated:{name}',
            origin={'file': entry['path'], 'line': entry['line'], 'source': entry['source'],
                    'derivation': 'economic_category_generator'},
            generated=entry)

    def all_symbols(self):
        """Every dynamic symbol, materialised once for the fuzzy retrieval index.

        Exact lookup builds symbols on demand; the retrieval index needs the whole
        set up front, because an LLM guessing a name has no way to know whether it
        came from the corpus or from game/mod data.
        """
        if self._all_symbols is None:
            index = self.index
            symbols = []
            if index is not None:
                for type_name, entries in sorted(index.by_type.items()):
                    kind = KIND_BY_TYPE.get(type_name, type_name)
                    for definition in entries.values():
                        symbols.append(DynamicSymbol(
                            name=definition.name, kind=kind, canonical_type=type_name,
                            path=definition.rel_path, id=definition.id,
                            origin={'file': definition.rel_path, 'line': definition.line,
                                    'source': definition.source, 'definition_type': type_name},
                            definition=definition))
            for name in self.modifiers():
                symbols.append(self.symbol_for_modifier(name))
            self._all_symbols = symbols
        return self._all_symbols

    def symbols(self, name):
        """Every exact-name dynamic symbol: indexed definitions, then generated names."""
        result = []
        index = self.index
        if index is not None:
            for type_name, entries in index.by_type.items():
                definition = entries.get((name or '').casefold())
                if definition is None:
                    continue
                result.append(DynamicSymbol(
                    name=definition.name,
                    kind=KIND_BY_TYPE.get(type_name, type_name),
                    canonical_type=type_name,
                    path=definition.rel_path,
                    id=f'{definition.id}',
                    origin={'file': definition.rel_path, 'line': definition.line,
                            'source': definition.source, 'definition_type': type_name},
                    definition=definition))
        generated = self.symbol_for_modifier(name)
        if generated is not None:
            result.append(generated)
        return result

    @property
    def localisation(self):
        """Display names of the loaded sources, built on first use (like call sites)."""
        if self._localisation is None:
            if not self.available or self.environment is None:
                return None
            try:
                self._localisation = gamedata.build_localisation_index(self.environment)
            except Exception:  # noqa: BLE001 - a failed scan must never break a lookup
                self._localisation = gamedata.LocalisationIndex()
        return self._localisation

    @property
    def call_index(self):
        """Identifier call sites, built on first use.

        The scan costs seconds, so it is never part of server startup: only an
        identifier lookup that can actually show call sites pays for it.
        """
        if self._call_index is None:
            if not self.available or self.environment is None:
                return None
            try:
                self._call_index = gamedata.build_call_index(self.environment)
            except Exception:  # noqa: BLE001 - a failed scan must never break a lookup
                self._call_index = gamedata.CallIndex()
        return self._call_index

    def lookup(self, name):
        """Exact game/mod declaration(s) for a name: the index without a query spelling.

        Used to grade a fuzzy retrieval hit: the fuzzy index only knows *names*, so a
        candidate reached from a partial query (``paladin`` -> ``paladin_ship``) would
        otherwise be reported as a spelling suggestion even though the name is a real
        declaration in the loaded game/mod data.
        """
        return self.symbols(name) if self.built else []

    def definitions_of(self, kind, name):
        """Dynamic definition matching one CWT kind (``trigger``/``effect``)."""
        wanted = {type_name for type_name, mapped in KIND_BY_TYPE.items() if mapped == kind}
        if not wanted:
            return None
        index = self.index
        if index is None:
            return None
        for type_name in sorted(wanted):
            definition = index.get(type_name, name)
            if definition is not None:
                return DynamicSymbol(
                    name=definition.name, kind=kind, canonical_type=type_name,
                    path=definition.rel_path, id=definition.id,
                    origin={'file': definition.rel_path, 'line': definition.line,
                            'source': definition.source, 'definition_type': type_name},
                    definition=definition)
        return None

    # endregion

    # region placeholder verification

    def verify_captures(self, captures):
        """Annotate template substitutions with real object existence."""
        if not captures:
            return captures
        return [{**item, **self._verify(item.get('placeholder'), item.get('value'))}
                for item in captures]

    def verify_reference(self, placeholder, value):
        """Verify one literal ``<object_type>`` value against game/mod definitions.

        Template placeholders are part of the startup index. Scalar references are much
        broader (technology, trait, event, ...), so missing types are scanned lazily and
        cached instead of making every server startup parse the whole game tree.
        """
        return self._verify(placeholder, value)

    def _reference_index(self, type_name):
        base = self.index
        if base is None:
            return None
        if type_name in (self._types or ()):
            return base
        if type_name not in self.db.types:
            return None
        if type_name not in self._reference_indexes:
            self._reference_indexes[type_name] = gamedata.build_index(
                self.db, self.environment, types={type_name})
            watched = set(self._types or ()) | set(self._reference_indexes)
            self._fingerprint = tuple(gamedata.fingerprint(self.db, self.environment, watched))
        return self._reference_indexes[type_name]

    def _verify(self, placeholder, value):
        if not placeholder or not value:
            return {}
        if not self.enabled:
            return {'object_existence': 'UNRESOLVED'}
        if placeholder.startswith('enum['):
            name = placeholder[5:-1]
            known = _enum_values(self.db, name)
            if not known:
                return {'object_existence': 'UNVERIFIED',
                        'object_note': f'enum[{name}] is not a simple enum in the loaded corpus.'}
            folded = value.casefold()
            return {'object_existence': 'CONFIRMED' if folded in known else 'NOT_FOUND',
                    'object_type': f'enum[{name}]'}
        if placeholder == DERIVED_PLACEHOLDER:
            return self._verify_economic(placeholder, value)
        name = placeholder[1:-1] if placeholder.startswith('<') else placeholder
        type_name, _, subtypes = name.partition('.')
        index = self._reference_index(type_name)
        if index is None:
            return {'object_existence': 'UNVERIFIED',
                     'object_note': f'{type_name} is not indexed from game/mod data.'}
        requested = type_name in set(index.stats.get('types_requested') or ())
        incomplete = bool(index.stats.get('truncated') or index.stats.get('errors'))
        if not requested or (not index.has_type(type_name) and incomplete):
            return {'object_existence': 'UNVERIFIED',
                    'object_type': type_name,
                    'object_note': f'{type_name} could not be indexed completely from game/mod data.'}
        definition = index.get(type_name, value)
        if definition is None:
            candidates = difflib.get_close_matches(value, index.names(type_name), n=5, cutoff=0.55)
            result = {'object_existence': 'NOT_FOUND', 'object_type': type_name,
                      'object_note': f'No {type_name} named {value} in the loaded game/mod data.'}
            if candidates:
                result['candidates'] = candidates
            return result
        if subtypes and subtypes not in definition.subtypes:
            return {'object_existence': 'UNVERIFIED', 'object_type': type_name,
                    'object_note': f'{value} does not match subtype {subtypes}.'}
        return {'object_existence': 'CONFIRMED', 'object_type': type_name,
                'resolved_from': {'source': definition.source, 'path': definition.rel_path,
                                  'line': definition.line}}

    def _verify_economic(self, placeholder, value):
        """Resolve ``<economic_category>[_<resource>]`` against real declarations."""
        index = self.index
        if index is None:
            return {'object_existence': 'UNRESOLVED'}
        folded = value.casefold()
        categories = index.by_type.get('economic_category', {})
        resources = index.by_type.get('resource', {})
        if folded in categories:
            return {'object_existence': 'CONFIRMED', 'object_type': 'economic_category',
                    'resolved_from': _origin(categories[folded])}
        head, separator, tail = folded.rpartition('_')
        if separator and head in categories and tail in resources:
            return {'object_existence': 'CONFIRMED',
                    'object_type': 'economic_category + resource',
                    'resolved_from': _origin(categories[head]),
                    'resource_from': _origin(resources[tail])}
        return {'object_existence': 'NOT_FOUND',
                'object_note': f'{value} is neither an economic category nor '
                               f'an economic category plus resource.'}

    def verify_enum(self, name, value):
        """Resolve a corpus ``complex_enum`` against values harvested from game/mod data."""
        sources = self.db.complex_enum_sources
        source_types = {type_name for type_name, entries in sources.items()
                        if any(enum_name == name for enum_name, _ in entries)}
        if not source_types:
            return {'object_existence': 'UNVERIFIED'}
        index = self.index
        if index is None:
            return {'object_existence': 'UNRESOLVED'}
        known = set()
        for type_name in source_types:
            for definition in index.by_type.get(type_name, {}).values():
                known.update((definition.data.get('complex_enums') or {}).get(name, ()))
        if (value or '').casefold() in known:
            return {'object_existence': 'CONFIRMED', 'object_type': f'complex_enum[{name}]'}
        requested = set(index.stats.get('types_requested') or ())
        complete = (source_types <= requested and not index.stats.get('truncated')
                    and not index.stats.get('errors')
                    and all(index.has_type(type_name) for type_name in source_types))
        if complete:
            return {'object_existence': 'NOT_FOUND',
                    'object_type': f'complex_enum[{name}]'}
        return {'object_existence': 'UNVERIFIED',
                'object_note': f'complex_enum[{name}] could not be indexed completely.'}

    # endregion

    def report(self):
        index = self.index  # force the lazy build before snapshotting anything
        environment = self.environment
        return {
            'enabled': self.enabled,
            'reason': self.reason,
            'seconds': self._seconds,
            'truncated': self._truncated,
            'watch': {'enabled': self.watch, 'interval_seconds': self.interval,
                      'rebuilds': self._refreshes},
            'environment': environment.as_dict() if environment is not None else None,
            'index': index.report() if index is not None else None,
            'generated_modifiers': len(self.modifiers()) if self.enabled else 0,
        }


def _origin(definition):
    return {'source': definition.source, 'path': definition.rel_path, 'line': definition.line}


def _block_values(node, key):
    block = node.field(key) if node is not None else None
    if block is None:
        return []
    result = list(values_like(block))
    return result


def attach(db, environment=None, enabled=True, watch=True):
    """Build (once) and cache the registry on a ``Database`` instance."""
    registry = getattr(db, '_dynamic_registry', None)
    if registry is None:
        registry = DynamicRegistry(db, environment, available=enabled, watch=watch)
        db._dynamic_registry = registry
    return registry
